### ISSUE TITLE
Content Removal

### ISSUE THREAD

**Issue by s0md3v** [0xInfection/Awesome-WAF#4]
Hi @0xInfection ,

As we discussed earlier, this _collection_ contains 6 XSS bypasses that were discovered by me and were published as a part of my research paper and I don't want them to be a part of this _collection_.
Please remove them as soon as possible.

Thank you.

**Comment by 0xInfection** [comment]
Will be addressed to shortly.

**Comment by 0xInfection** [comment]
c1f09e0b FTW!

**Comment by s0md3v** [comment]
Hi @0xInfection ,

I don't have any issue with my name by being included or my other works such as my paper, AwesomeXSS or XSStrike being included in here.\
I just want my payloads to be removed from here.

Thank you.

**Comment by 0xInfection** [comment]
What are talking about? 🤔 I included the payloads from a random research paper I came across.

**Comment by s0md3v** [comment]
That's all you had say.

Now listen here,
If you publish something without a LICENSE (which I did), then according to the international standards, it is automatically copyrighted in a way that no one can use, modify and re-distribute it even with proper credits.
I guess you don't know much about giving cr...nvm. Let's keep it to the point.

I will speak with Github team and you are free to delete or archive this issue.

Thank you.

**Comment by 0xInfection** [comment]
Alright since it has come to this, let's do the real talking now:
1. Well whatever your talking about apples to code repositories. Yours only a paper. 
2. I had given credits initially, which was not okay with you. Now I removed the associations and __directly referenced your paper__. And as said before, __I have just curated the stuff__, nothing more.
3. You are most welcome to have a talk with GitHub team. Keep me updated about the your improvements.

**Comment by s0md3v** [comment]
It wouldn't have come to this if you respected my request as the author of the concerned content.
I will reply no further now and leave the rest to Github support.
